### ISSUE TITLE
HTTP authentication and proxy authentication hook

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#119]
This part of http://fetch.spec.whatwg.org/ is not defined super well at the moment. Basically, for both synchronous and asynchronous requests, if the response is a 401 or a 407 we might have to prompt the user and pause the request operation. At least for preserving existing behavior of e.g. <img> and XMLHttpRequest such.

We need to carefully consider what to do for fetch() and workers in general.

And we should make put clear specification-based callback hooks in Fetch that I suppose will have to be implemented by a global object or some such, rather than an API end point.

**Comment by annevk** [comment]
Reopening since this is actually a serious problem that needs addressing one way or another. E.g. currently `fetch()` disables HTTP authentication which might be incompatible with what we actually need to do.

**Comment by annevk** [comment]
Dialogs affected: HTTP auth, HTTP proxy auth, TLS client auth.

According to @sleevi we cannot simply disable all protocol-triggered dialogs for service workers. (Would this be true even if we have an API for sites to do TLS client auth?)

Difficult scenarios:

* Decide which browsing context to spam (does the originating client need to be cloned across Request objects? what if you just supply a URL to fetch()?)
* What happens if there are no browsing contexts open?
* ...?
* No profit.

**Comment by annevk** [comment]
See also:

* https://twitter.com/sleevi_/status/612520002743369728
* https://code.google.com/p/chromium/issues/detail?id=329884#c26

**Comment by jakearchibald** [comment]
Could `client.fetch(request)` be a way to make a request in the context of another client. Any UI required by the request would be shown in that client if it's a `WindowClient`.

**Comment by annevk** [comment]
I think we should first try to figure out what the current setup should or shouldn't do before adding yet more features.

**Comment by jakearchibald** [comment]
From IRC discussion:

If `fetch(url)` is initiated from a dedicated worker or document, it can use the top level window of the associated document for UI if required.

For `fetch(url)` within SharedWorkers, UI should be shown in the top level window associated with one of the associated documents of the SharedWorker.

For `fetch(url)` within ServiceWorker, UI should be shown in the top level window associated with one of the controlled window clients.

In cases where there are multiple choices, the browser should prioritise focused windows, over visible windows, over others.

**Comment by annevk** [comment]
That a) leaves out the case where there are no windows and b) is not what I think the ideal solution is here. I think the ideal solution is still for `fetch()` to never trigger browser UI and add some kind of API so you handle TLS client auth yourself, just like you can already with HTTP auth. Triggering browser UI for HTTP auth is actually a "feature" most developers dislike. They'd rather handle that prompt themselves. I'd assume the same is true for TLS client auth.

**Comment by jakearchibald** [comment]
Ahh yes, in the case of no windows to show UI, the request should reject.

Will think about the UI thing. I need to learn more about how these types
of requests happen.

**Comment by sleevi** [comment]
I'm fairly certain that both the Shared Worker and the Service Worker proposal by @jakearchibald  won't really be something we can reliably/safely implement in Chrome, and would definitely be something the Chrome networking team would push back on for implementation in layering concerns. It's also fairly non-deterministic.

From the networking side, David and I are fairly supportive of the "Request in a [Shared/Service]Worker that would result in UI gets aborted" as the baseline, and then trying to iterate in a way that may allow some interaction iff the *Worker can deterministically control it, and the user agent can mediate it.

But to @annevk 's point of allowing client auth to be controlled in the way HTTP auth is, that's also a bit of a non-starter on the grounds of privacy/security. We can't reveal anything about the certificates available (they're rife with PII and persistent identifiers that are potentially non-revocable) without some form of prior user mediation, and in a way that's at least quasi-understandable by users (read: "Do you want this website to know everything about you?" *isn't* that :-1: )

**Comment by annevk** [comment]
Client auth: Could we have an API within the document environment that triggers client auth UI and returns an opaque object you can use with a request (and message to a worker)? Is there some way to figure out if the server challenges you for client auth?

Workers: Does Chrome never trigger UI in workers? Not even for HTTP proxy auth? It would certainly be my preference that workers cannot trigger UI and `fetch()` cannot either.

**Comment by sleevi** [comment]
> Client auth: Could we have an API within the document environment that triggers client auth UI and returns an opaque object you can use with a request (and message to a worker)? Is there some way to figure out if the server challenges you for client auth?

To do that would force a design constraint on client auth implementations that wouldn't be compatible with Firefox's current implementation, though compatible with Chrome's only through a (undesired) backwards compatibility quirk from when Chrome shared the same networking stack as IE (WinInet) before introducing its own network stack.

If you forced fetch() to invoke some user-level callback/promise during the authentication flow (to give an opaque object and let the S*W determine whether or not to prompt or not), then that design would be incompatible with Chrome's implementation, but compatible with FF's, but somewhat undesirable due to introducing a whole new host of edge cases that app developers would potentially have to work around (this is an issue FF already has w/r/t edge cases and non-determinism).

So both end up in a somewhat weird/undesirable state.

> Workers: Does Chrome never trigger UI in workers? Not even for HTTP proxy auth? It would certainly be my preference that workers cannot trigger UI and fetch() cannot either.

Due to the complexities of Chrome's current SW implementation, I don't have an answer based on first principles/code inspection. It's one of those "¯\_ツ_/¯" situations where whatever we due experimentally isn't necessarily because of any intentionality of design or expectation of behaviour.

An initial solution would be "Don't prompt at all", which is far more consistent and reasonable. A longer term solution worth exploring is whether we can use the [FetchEvent.client](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#fetch-event-interface) into the [RequestInit](https://fetch.spec.whatwg.org/#requestinit), such that any user interaction happens in the context of the [Client](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#client-interface).

That is, in order to make a sensible story for prompting, I think our inclination is there needs to be some way for the S*W to tag the fetch() invocation with the client - either through [GlobalFetch](https://fetch.spec.whatwg.org/#fetch-method) having a way to specify the client, or by having [Client](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#client-interface) implement `GlobalFetch` as a specialization of the general Fetch. I'm more inclined to make it the 'explicitly supplied via RequestInit' than 'implicitly supplied based on object you're calling', but what do I know?

**Comment by annevk** [comment]
Client certificates: So per https://tools.ietf.org/html/rfc5246#section-7.4.6 it seems the client certificate challenge is different enough from HTTP auth that it would require quite a few API additions, which, combined with the fact that client certificates are rarely used, would not be worth doing.

If we need to maintain client certificate support for organizations that stepped into that trap I agree with @sleevi that we should have a simple way to opt into that, e.g.
```js
var resp = fetch(url, { clientCertificateWindow: fetchEvent.client })
```
It makes `fetch()` less clean inside service workers (do we need it elsewhere?), but so be it.

Mixed Content: Requests in a service worker can affect the address bar icon. It seems though that mixed content warnings should affect all open windows and if there are no open windows we should treat this as a network error. So this should probably be a separate flag of sorts set by Service Workers that allows Fetch and Mixed Content to deal with this scenario?

HTTP auth: If you want this bring your own UI.

HTTP proxy auth: Network error, including for window? Would be great if we could do that for `fetch()` I think. Otherwise we should have something similar to client certificates for this.

**Comment by jakearchibald** [comment]
> `var resp = fetch(url, { clientCertificateWindow: fetchEvent.client })`

So this is how I came to `client.fetch()`. I guess this creates a divergence between the fetch options and the request options. Not that that's a bad thing. Is this association specific to client certs, or is it a more general link between the client and request? Would it affect referrer for instance? Would the client ceasing to exist trigger the termination of the fetch?

**Comment by sleevi** [comment]
> It makes fetch() less clean inside service workers (do we need it elsewhere?), but so be it.

I think any time where a fetch() API is explicitly being called, we will need some way to discuss the clients.

> Mixed Content: Requests in a service worker can affect the address bar icon. It seems though that mixed content warnings should affect all open windows and if there are no open windows we should treat this as a network error. So this should probably be a separate flag of sorts set by Service Workers that allows Fetch and Mixed Content to deal with this scenario?

That's https://github.com/whatwg/fetch/issues/69 , which I'm about to chime in on, because Chrome networking, security, and SW teams have discussed this extensively w/r/t Chrome's UI

> HTTP auth: If you want this bring your own UI.

I'm sorry, but that fundamentally doesn't work, because it breaks the pass-through SW case where you're talking to a third-party origin.

That is, I can't use
```
onFetch(fetchEvent) {
  fetchEvent.respondWith(fetch(fetchEvent.request))
}
```
if fetchEvent.request may result in auth.

So that's why I think the client issue is more generalized, and explicitly not limited to just client certificates.

> HTTP proxy auth: Network error, including for window? Would be great if we could do that for fetch() I think. Otherwise we should have something similar to client certificates for this.

s/similar/the same/ - I don't think users or implementors benefit from trying to justify the client on a case by case basis, especially so you don't end up with scenarios like:

```
onFetch(fetchEvent) {
  fetchEvent.respondWith(fetch(Request(fetchEvent.request, {
    clientCertificateClient: fetchEvent.client,
    httpAuthClient: fetchEvent.client,
    proxyAuthClient: fetchEvent.client,
    froobleFrazzleClient: fetchEvent.client
  })));
}
```

Instead, if we just do either
```
onFetch(fetchEvent) {
  fetchEvent.respondWith(fetchEvent.client.fetch(fetchEvent.request));
}
```
or
```
onFetch(fetchEvent) {
  fetchEvent.respondWith(fetch(Request(fetchEvent.request, { client: fetchEvent.client; })));
}
```

Then they both seem better. And we can define an implicit client for those implementing the [GlobalFetch](https://fetch.spec.whatwg.org/#globalfetch) interface if the Request.client is undefined, which means that you can still do `fetch(url)` or `fetch(Request(url))` and have it Just Work

**Comment by annevk** [comment]
> [I]t breaks the pass-through SW case where you're talking to a third-party origin.

This is observable through redirects (unclear how to fix), referrer (can fix, except for "no-cors" CSS subresources), CSP (there's a proposal of sorts, but disallowed requests will be made, context will get lost), and presumably more since I doubt I hit the bottom. Pass-through works, but `fetch()` is not pass-through. It does a number of things to a request.

I agree that request and clients are bound. The split `FetchEvent` made never sat well with me (and you'll find Fetch doesn't have it). I do think network-spawn dialogs need to be an opt-in choice though.

**Comment by jakearchibald** [comment]
@annevk I'm open to moving `fetchEvent.client` into the request as long as you're fine with it being stripped out as it goes into the cache.

**Comment by sleevi** [comment]
> I do think network-spawn dialogs need to be an opt-in choice though.

Really? Why is that? I'm having trouble thinking of a reason where it's desirable to do that. For Chrome, we have something similar to fetch() as a C++ API for different components to use. Pretty much _everyone_ gets that flag bit wrong and it violates user expectations.

**Comment by annevk** [comment]
@jakearchibald seems fine. Though the cache actually poses an interesting challenge. If you fetch a mixed content "no-cors" successfully and put it in the cache. And then close all tabs and come back, will the browser show mixed content? Where is that defined?

@sleevi the idea was for `fetch()` to have the minimum amount of magic by default. Network-spawn dialogs are pretty magic. I wonder what @domenic thinks. I guess I'm okay defaulting though if we have some kind of `{ client: null }` override (set all the time in dedicated/shared workers) if that is all that remains solving this puzzle.

**Comment by annevk** [comment]
(It seems the Mixed Content cache question is addressed for Chrome in https://code.google.com/p/chromium/issues/detail?id=392409#c48 but not in the specification.)

**Comment by jakearchibald** [comment]
I agree with the behaviour there (not just because it's what we do, I was just typing the same thing up before you posted that, honest guv).

The response url is good enough for this check right?

**Comment by annevk** [comment]
Yeah it should be.

**Comment by sleevi** [comment]
The response URL is only good enough if you can't CORS the HTTP data. If you can, then you have to do more tainting. So, at the least, keeping mixed-content Opaque (if permitted) is how to avoid the Cache issue.

Unless I'm confused as to "the response url is good enough"

(Also, redirects + mixed-content & all that jazz that seem to affect SW moreso than https://github.com/whatwg/fetch/issues/69 but for which I suspect is yet-another-bug)

**Comment by jakearchibald** [comment]
I mean, in the spec, if the SW returns a response with an http url (it'd always be opaque) we tell the client to react to mixed content.

Actually, maybe "accepts mixed content" should be a request flag within fetch, then fetch can decide whether to just reject on an insecure response or trigger mixed content warnings.

**Comment by sleevi** [comment]
> Actually, maybe "accepts mixed content" should be a request flag within fetch, then fetch can decide whether to just reject on an insecure response or trigger mixed content warnings.

*Exclusively* that doesn't work if the flag changes over time (and it will). If the initial fetch() had the flag set (and allowed), then was entered into the Cache, then later the client changed (e.g. say they went HSTS and started blocking optionally-blockable content), then if the Response was served from the Cache, it'd be serving mixed content.

If the flag is there, it's arguably an optimization, not a security boundary. And it's an optimization that may not be needed if there was, say, streaming (since you could defer initializing the stream/sending the request until surfacing the Response to the Client)

Anyways, I suspect this is yet-another-bug, so maybe we should fork it off.

**Comment by jakearchibald** [comment]
> then if the Response was served from the Cache, it'd be serving mixed content.

Right, and fetch would reject in that case because the request would not "accepts mixed content". That seems fair.

Take your point though that the decision to show mixed content could sit with the consumer, just comes down to changing one spec vs many.

**Comment by annevk** [comment]
https://fetch.spec.whatwg.org/#main-fetch already invokes Mixed Content for both requests & responses. https://w3c.github.io/webappsec/specs/mixedcontent/#should-block-response does not define degrading UI though. I guess that needs to be fixed...

**Comment by annevk** [comment]
I filed https://github.com/whatwg/fetch/issues/70 for the API that needs to be added to Fetch. Leaving this open for the various other things that were mentioned that we haven't followed up on yet.

**Comment by annevk** [comment]
https://github.com/w3c/webappsec/issues/413 and https://github.com/w3c/webappsec/issues/409 cover the referrer thing.

I guess https://github.com/slightlyoff/ServiceWorker/issues/607 covers the redirect issue. Seems like one of the more prominent service workers is not a pass-through mechanism examples.

CSP is https://github.com/w3c/webappsec/issues/227

Anything else?

**Comment by domenic** [comment]
> @sleevi the idea was for fetch() to have the minimum amount of magic by default. Network-spawn dialogs are pretty magic. I wonder what @domenic thinks.

If I am understanding the situation correctly: as an author using fetch, I would expect to get a 401 Response object, with no user prompting ever. Then I could maybe cook up and supply an `Authorization` header. Possibly I would do that by asking the user (using a much nicer form than the browser one!) to enter a username and password; possibly I would use cookies; etc. etc.

I don't understand why anything else would be desirable.

**Comment by sleevi** [comment]
> Possibly I would do that by asking the user (using a much nicer form than the browser one!) to enter a username and password;

We call that phishing :)

> possibly I would use cookies;

That's not how HTTP auth works :)

> I don't understand why anything else would be desirable.

What you described cannot be implemented without crippling the platform and harassing users.

The TL;DR: is what you described can only be polyfilled for simple cases (which no one uses), not for the hard cases (for which a non-trivial, rather large position of our users use, and for which I guarantee you use every day without ever realizing)

Hopefully without sleevi-splaining too much, that simply doesn't work. There are authentication mechanisms that cannot be polyfilled by Javascript because they rely on interacting with the user and host OS (e.g. NTLM, Negotiate, Kerberos) in a way that's designed to be extensible (so we can't just spec all the ways because there are an infinite number of them) and, more importantly, to keep credentials opaque (and I mean opaque from the browser itself).

Imagine if Site X wants to use a Service Worker, and it wants to load resources from Site Y and Z (Z could be an intranet site, a vendor site, whatever). The SW only cares about loads/caching from Site X, but the Site Y/Z loads come in by virtue of us shunting all requests through the SW. In today's browsers, "magic" or not (really, it's a defined security boundary, and one we shouldn't just chuck out because it makes things hard), if a user has visited Z, we don't prompt them for credentials if we have them, and, on many platforms, we can avoid prompting for credentials all together by interacting with the OS in ways we absolutely must never expose to websites (in the most literal sense of never)

So you can't "polyfill" auth in these scenarios, and were you to, it would be detrimental to user security.

Now, if you're Site X talking about resource from fetch(X), then it still remains a case-by-case decision. A SW shouldn't have to (securely) maintain a credential store for X, and it should be able to share that credential with other loads (SW or not) and other subsystems. The solution you described simply doesn't allow for that.

**Comment by domenic** [comment]
I guess I see. The flow I am describing is how it works server-side, which is what I anticipated a "low-level" API would provide.

**Comment by annevk** [comment]
@domenic I think my new way of thinking about `fetch()` is that it does fetching the same way XMLHttpRequest et al approach it, but that you can opt-out of the "magic". E.g. in this case by setting client/dialogWindow to null. (Of course, as @sleevi indicates not all "magic" can be handled by JavaScript, but simple HTTP authentication flows certainly can, and I agree would indeed be better.)

**Comment by annevk** [comment]
I recommend that if there are more concerns about this approach we discuss them in one of the dedicated tickets I pointed to above. This thread is splintered enough as-is. And if you have a novel issue, please open a new one.
