### ISSUE TITLE
Why does update() not return the promise from _Update

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#311]
Might want to indicate this somewhere with a note of sorts. _Update being asynchronous makes it even weirder that update() feels the need to queue a task btw.

**Comment by jungkees** [comment]
I'm trying to think of what kind of benefits we can give to devs by exposing the Update promise to script? One can be allowing devs to catch update errors and the reasons, otherwise it would be silently ignored and the existing active worker will continue to serve the requests anyway. For the successful update case, I don't see a big gain as the promise will resolve with the same registration object which the update() method was invoked on. Any idea what'd be a better decision here?

**Comment by annevk** [comment]
It seems somewhat confusing to use promises in the internal algorithms if they're not actually exposed to script.

**Comment by jakearchibald** [comment]
Agree with @annevk here.

`reg.update()` should return a promise that resolves if the update completes successfully (even if no new SW is created as a result), it rejects if there's a network error.

The resolved value should be undefined, as you already have the registration.

**Comment by jungkees** [comment]
Tracked in http://crbug.com/513655.
