### ISSUE TITLE
SW spec never hooks into the "runs a worker" term that the CSP spec uses to enforce CSPs

### ISSUE THREAD

**Issue by jyasskin** [slightlyoff/ServiceWorker#378]
https://w3c.github.io/webappsec/specs/content-security-policy/#processing-model-workers says "Whenever a user agent _runs a worker_: …", but https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html never updates the definition of "_run a worker_" from http://www.whatwg.org/specs/web-apps/current-work/multipage/workers.html#run-a-worker nor mentions the `Content-Security-Policy` header in order to apply it directly.

**Comment by jungkees** [comment]
@jyasskin Due to the different lifecycle and the processing model, SW spec defines [Run Service Worker](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#run-service-worker-algorithm) algorithm instead of hooking into Worker's run a worker algorithm. Run Service Worker, when called, runs already fetched service worker script, and the actual script fetching is done in Update algorithm step 4.3.7. Do you have any suggestion how to enforce CSPs for SW?

**Comment by jyasskin** [comment]
You would need to look at how it's done in the "run a worker" algorithm. You may also have to send @mkwst a patch for the CSP spec so it has a hook for SWs.

**Comment by jungkees** [comment]
I brought the text from CSP spec to SW Security Considerations section for now: https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#content-security. When things are settled on CSP.next, we may just link to CSP. Note that the origin's globally unique identifier check step is omitted as the script's origin should not be a globally unique identifier once it gets to the point where it can invoke Run Service Worker algorithm.

Closing.
