### ISSUE TITLE
unregister() then register() same-scope, different script URL that fails: what do you expect to happen?

### ISSUE THREAD

**Issue by mattto** [slightlyoff/ServiceWorker#396]
Can a spec editor look over these tests to see if it's asserting what you intended?
https://codereview.chromium.org/416003003/diff/100001/LayoutTests/http/tests/serviceworker/unregister-then-register.html?context=10&column_width=140

I wrote them as spec'd but it may be counterintuitive. Basically, suppose you register a SW, make it a controller, then unregister it, then register for same-scope but new script URL, and that register fails (due to 404, parse error, or install failure). You might expect the original registration to be unregistered, but as currently spec'd it lives on.

Related to Issue #371

**Comment by nikhilm** [comment]
Would be awesome if this was fixed to FIFO queues so the spec and implementations were congruent!

**Comment by jungkees** [comment]
The current algorithms guarantee the execution of the requests in FIFO order. I discussed this with @slightlyoff F2F during the last TPAC, and we came to a conclusion that the current algorithms are reasonable considering the fact that the requests can be initiated from different tabs and workers at any time.

**Comment by jungkees** [comment]
To sum, register/update/unregister runs in FIFO order with the following noticeable behaviors:
(1) When an unregister is queued, the next register* request will wait until the registration for the unregister is deleted from the map. (the register* resolves and gets to installed state to be ready though.)
  - This guarantees concurrently running clients are always using the same version of service worker.

(2) Undo the unregister when the next register is for exactly the same registration for the same script.

Closing.

**Comment by mattto** [comment]
Thanks for the clarification Jungkee, this is what Chromium is doing (rather, it will be once https://code.google.com/p/chromium/issues/detail?id=445151 is fixed).

In addition to FIFO order, Chromium does "make all the others block until the first one is done" behavior. The one exception is that a running register job waiting in the 'installing' state gets aborted whenever another register job for that scope is scheduled to run later in the queue. This stops waitUntil(new Promise({}) from blocking the queue.

Also, as Michael mentioned, Chromium also coalesces multiple sequential calls with the same inputs into one job in the queue.

I believe all of these are acceptable as per the spec.

**Comment by nikhilm** [comment]
The way it is currently framed, a worker can block the activate task by e.waitUntil(new Promise({})) which holds up the entire queue. It would be better to remove Step 13-14 from the atomic constraints and have them check that the registration hasn't started uninstalling and the active worker is still valid.

**Comment by nikhilm** [comment]
I also don't understand why these 2 steps are required in the new location:

    Wait until a Record {[[key]], [[value]]} entry of its scope to registration map where registration's scope url matches entry.[[key]] is deleted.
    Set a newly-created Record {[[key]]: registration's scope url, [[value]]: registration} to scope to registration map.

It seems to me the problem to be solved is:
1) If an [[Unregister]] was called before this [[ContinueInstalling]]'s (My name for step 7 of [[Install]], after waiting on the queue) matching [[Register]], we want to treat the unregister as never happening since this register replaced it. So we could just set the uninstalling flag to false.
2) Otherwise, if [[Unregister]] was called between the [[Register]] and [[ContinueInstalling]] (the worker took a long time to fetch resources or something), we want to let unregister win. Which means if the timestamp of setting unregister was later then we can just abort these steps.

**Comment by jungkees** [comment]
> The way it is currently framed, a worker can block the activate task by e.waitUntil(new Promise({})) which holds up the entire queue. 

It seems that's what exactly `e.waitUntil()` means to do. The activate task should wait on this as it change s the worker's state upon the completion of the task queued on the worker.

For `e.waitUntil(new Promise({}))` kind of usage, we added this text in 4.4: "The service worker should not be terminated until the result of waiting for all of the extend lifetime promises has been settled. However, the user agent may impose a time limit to this lifetime extension."

> It would be better to remove Step 13-14 from the atomic constraints and have them check that the registration hasn't started uninstalling and the active worker is still valid.

Could you elaborate some more about this?

**Comment by jungkees** [comment]
Re @nikhilm's https://github.com/slightlyoff/ServiceWorker/issues/396#issuecomment-73335779, my intention was to satisfy the condition (1) for https://github.com/slightlyoff/ServiceWorker/issues/396#issuecomment-71418536.

However, by reviewing those steps again, I think Install algorithm steps 7.8.1 - 7.8.2 can be removed as suggested. The Install request with later timeStamp than the uninstalling flag will never break the currently running active worker state anyway by waiting for all the controlled clients unload. 

@mattto, before removing those steps, let me know if you have any concerns.

**Comment by mattto** [comment]
@jungkees Yes, I agree those steps can be removed.

**Comment by nikhilm** [comment]
About comment https://github.com/slightlyoff/ServiceWorker/issues/396#issuecomment-73318943
It has to do with queuing. The timing exception is more of a sort-a-kinda fix to this, since it is impossible for a browser to determine if the worker is stuck, or being evil, or really doing something important, when deciding to time it out.

For installation, we have a install queue, and install result queue. What this allows is the splitting up of the install algorithm, gating the "set of steps before "install" event is sent to worker" on install queue and then "set of steps after "install" event is set to worker" on install result queue. What this means is that even if workerA is waiting for a long time in the install event, other workers for the same scope can continue to reach the install state (where they are sent the install event), before getting blocked.
On the other hand, since Activate is called from inside a set of atomic steps, instead of being called non-atomically and then having its own activation result queue, it means that no other workers get sent the activate event if a worker is currently handling the event. I was wondering if it could follow the installation pattern for consistency. I don't think it matters a lot :)

**Comment by nikhilm** [comment]
On the other hand, I do have a spec reconciliation question. Where the spec has 3 queues, Gecko and Blink (IIUC) have just one queue. So in the spec:

    register("a.js")
    register("b.js")

where A & A both have fairly long running oninstall handlers (say on the order of seconds)
results in both A and B's register+update proceeding, before B's [[Install]] observes that there is an already installing worker ([[Install]] step 4.1) and terminates A's installation.

In implementations, the same leads to B being immediately blocked (at [[Update]] Step 4.2.1) until A has transitioned to waiting.
Considering the API surface of serviceworkers, I'm sure this behaviour is observable. So we should agree on something. We should agree on 3 vs 1

I'm not sure if @mattto 's comment https://github.com/slightlyoff/ServiceWorker/issues/396#issuecomment-71590525 claims that Blink's behaviour is spec compliant since A is retroactively aborted.

**Comment by jungkees** [comment]
> On the other hand, since Activate is called from inside a set of atomic steps, instead of being called non-atomically and then having its own activation result queue, it means that no other workers get sent the activate event if a worker is currently handling the event. I was wondering if it could follow the installation pattern for consistency. I don't think it matters a lot :)

The invocation of Activate algorithm (Install step 9) is out of the atomic-step-block. And queuing a task in Activate step 1.11 is run in the same order as the invocation of the Activate algorithm itself as such. I'm not sure whether we have any case where more than two concurrently running Activate algorithms race for queuing a task.

I think the only improvement point here is we probably can divide the single atomic-step-block in Activate algorithm into two: 1.1 - 1.11 and the rest. It seems this will allow queuing a task to fire `activate` event  to be not block until the algorithm completes. But even in this case the queued tasked will run in the same order as in the current text.

**Comment by mattto** [comment]
@nikhilm Regarding the case of:
```
register("a.js")
register("b.js")
```

My reading of the spec is once "a.js" enters Update 4.3, "b.js" is free to enter Update 4.1 and it will now be the top element, so it proceeds to block on "a.js" exiting Update 4.3 since it is atomic. Once "a.js" exits Update 4.3, it enters Update 4.4 (Install) but in parallel "b.js" can enter Update 4.3 and also proceed to Update 4.4. So they both end up in Install, but "a.js" enters the atomic Install 4 first at which point it becomes "installing". Once it exits Install 4, "b.js" can enter Install 4 and which point it terminates "a.js". If I understand correctly, another possible sequence is "a.js" proceeds to finish install and activate before "b.js" enters Install 4; i.e., the spec allows racing here. Blink does the termination case (and is careful to do so only after "a.js" exits Install 4), which I think is OK per spec?

**Comment by jungkees** [comment]
Patch for https://github.com/slightlyoff/ServiceWorker/issues/396#issuecomment-73335779: 8cd565914d5405a58fede0b063c1730f88cb97ea.
