### ISSUE TITLE
Please deploy dfn.js or something similar

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#489]
https://resources.whatwg.org/dfn.js as it stands now it is too hard to find out where a given definition is referenced from.

**Comment by jakearchibald** [comment]
We should look to move to bikeshed

**Comment by mkruisselbrink** [comment]
Is the only thing stopping us from moving to bikeshed that nobody has volunteered yet to put in the work needed to do so? Or are there particular reasons why we might want to delay moving to bikeshed. If the consensus is that yes, we should move to bikeshed, I'd be happy to volunteer to do so (I've converted two other specs to bikeshed, so I've some idea what I'm signing up for, although those were of course way smaller than the service worker spec).

Anyway, some thoughts about the consequences of a conversion to bikeshed:

- Styling will be different, hopefully for the better.
- Deep links to sections and definitions should mostly remain the same, but links to IDL definitions will change as bikeshed doesn't have a way to specify your own anchors for those (even if it would I don't think we'd want to hardcode these anyway). Some section anchors might have to change too for this, since they conflict with the bikeshed generated IDL anchors.
- Any outstanding pull requests or other changes people are working on will have to be manually rebased. This also might be a reason to do the conversion while v1 and v2 haven't diverged too much yet, as then we can convert both without extra effort.
- Major changes to the spec while I'm working on the conversion to bikeshed would of course be annoying as I'd have to manually re-apply them on top of the bikeshed version. But the spec is probably stable enough at this point for this to not matter too much for however long this will take; re-applying a week (or a few weeks) worth of changes on top of a bikeshed conversion should be relatively painless.
- Actually reviewing the conversion might be hard, since it'll be a fairly substantial change. Although splitting the conversion in several commits might make this slightly better, in the end still pretty much every line of spec source will change for this:
  - one commit to update the overall structure to be bikeshed compatible while keeping most of the actual content unchanged
  - one commit to update definitions and references to them to be bikeshed compatible; we could choose to keep explicit links to locally defined terms to keep the diff somewhat managable (and optionally clean those up in a separate commit), or just go all the way and clean up internal links as well. Either way this will be a pretty nasty diff to review as it'll change so much all over the place.
  - other cleanups as we see fit.

So is there consensus that moving to bikeshed is a good thing, and if so, when would it make sense to do so?

**Comment by tabatkins** [comment]
> links to IDL definitions will change as bikeshed doesn't have a way to specify your own anchors for those

You can *if* you do a `<dfn>` for the construct outside of the `<pre class=idl>`.  Then Bikeshed will just link the IDL to your dfn.  This is common practice for methods and attributes, so their anchors are actually close to their prose definitions.

If you've been using the "WHATWG style" for IDL IDs (dom-foo-bar for the Foo.bar attribute, etc), Bikeshed does that by default, so the IDs will remain stable.

**Comment by tabatkins** [comment]
Note that Bikeshed does not currently have dfn.js built in.  You can just link it in yourself for now, I'm just noting that moving to Bikeshed will not actually solve the problem this issue was opened for. ^_^

(I'll be working on Bikeshed all this month, and I think dfn.js support is on my issues list, so maybe I'll fix it anyway, and you *can* close this issue just by porting.)

**Comment by mkruisselbrink** [comment]
> You can if you do a <dfn> for the construct outside of the <pre class=idl>. Then Bikeshed will just link the IDL to your dfn. This is common practice for methods and attributes, so their anchors are actually close to their prose definitions.

Ah, good point. Not sure why it never occurred to me to specify explicit ids for such dfn's. I guess because unlike for every other dfn bikeshed doesn't complain about having to auto-generate ids for them... I guess that just leaves the question if we want to use the auto-generated "whatwg style" ids or keep using the currently used explicit ones. Probably keeping IDs stable is a good idea in that case, since all the ids are there already so it's not actually any more work. For future additions using watwg style IDL IDs might make sense though.


> Note that Bikeshed does not currently have dfn.js built in. You can just link it in yourself for now, I'm just noting that moving to Bikeshed will not actually solve the problem this issue was opened for. ^_^

Ah, good point. I should have probably opened a separate issue for the actual bikeshed migration in that case. But it doesn't look like adding dfn.js support should be very hard either way.

**Comment by jungkees** [comment]
Having discussed with @slightlyoff, we agree to this conversion if bikeshed adds value in the way we collaborate and some convenience to the readers.

@mkruisselbrink, @slightlyoff added you as a collaboration in the repo. Please help us!

**Comment by wanderview** [comment]
If this removes the dynamic content/style updates, then it would make the spec easier for me to use.  Right now the scroll positions all change after navigating to a section anchor directly.  Very annoying.

**Comment by slightlyoff** [comment]
@mkruisselbrink has converted the spec to Bikeshed. Closing.

**Comment by mkruisselbrink** [comment]
Closing might be premature until tabatkins/bikeshed#469 is resolved and bikeshed actually includes dfn.js?

**Comment by tabatkins** [comment]
> Note that Bikeshed does not currently have dfn.js built in. You can just link it in yourself for now, I'm just noting that moving to Bikeshed will not actually solve the problem this issue was opened for. ^_^

**Comment by tabatkins** [comment]
Yes, Bikeshed conversion was a good idea, but as I said earlier, it's a diversion from the actual purpose of this thread, which is to get dfn.js on the spec.

**Comment by tabatkins** [comment]
Note: I've been building the dfn.js functionality directly into Bikeshed, so the panels are generated statically and only have a tiny JS dependency for the show/hide functionality. I plan to turn this on by default later today unless someone objects, so the conversion to Bikeshed was a good idea. ^_^
