### ISSUE TITLE
OCSP fetches bypass service worker

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#564]
At least, I'm assuming they will. I wonder what the best way of defining that will be. Ideally in the OSCP specification, but it seems unlikely they'll integrate with Fetch anytime soon. Perhaps Fetch needs to "monkey patch" it...

**Comment by jakearchibald** [comment]
I'm closing this. Assuming this request will be made without a client. Reopen if this isn't right.

**Comment by annevk** [comment]
I think that isn't right, since we have other requests without a client that do go through the service worker. E.g., reports.

**Comment by jungkees** [comment]
Agreed on "Fetch needs to "monkey patch" it" for now.

**Comment by jakearchibald** [comment]
Pre F2F notes: is this still an issue?

**Comment by annevk** [comment]
It's still not defined I think.

**Comment by jakearchibald** [comment]
F2F:

* Implementations do this at a much lower level than the browser networking stack
* It absolutely shouldn't go through SW
* Fetch doesn't currently talk about fetching certs, seems to defer to TLS - do we need to specify that this doesn't go through SW
* If so, we can solve it in fetch

**Comment by jungkees** [comment]
@annevk, is there any spec work where they will invoke fetch with OCSP request? If yes, they seem to have to set the flag there. Otherwise, fetch seems a right place to either monkey patch or leave non-normative comments. Should I file it to fetch?

As an aside, if we replace skip-service-worker flag with just using/checking a client's global's service worker value, OCSP request won't even have to set the flag as the request won't go through registration matching in the first place.

**Comment by annevk** [comment]
Yeah, I guess you can file it against Fetch.

Note that not all requests will have a client. E.g., if I enter example.com into the address bar, there won't be a client there, but we'll activate example.com's service worker for sure.

**Comment by jungkees** [comment]
This issue has been moved to fetch: https://github.com/whatwg/fetch/issues/347.
