### ISSUE TITLE
Background caching

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#574]
Adding this as a placeholder for a problem we need to solve at some point.

If I'm caching a large resource I'm likely to close/hide the browser, go do something else, but still expect the cache to update. Thinking about audio/video here, but also large game assets. In these cases it's likely the ServiceWorker will be shut down and presumably caching will fail.

We need another way. Something that will let the SW shut down and open again on completion.

Eg

```js
self.addEventListener('push', function(event) {
  event.waitUntil(
    fetch('/large-audio.mp3').then(function(response) {
      if (response.status != 200) throw Error("Nahhhh");
      
      return caches.open('music').then(function(cache) {
        return cache.backgroundPut('/large-audio.mp3', response);
      });
    })
  )
});

self.addEventListener('backgroundcachesuccess', function(event) {
  event.cacheName; // 'music'
  event.request.url; // 'https://origin/large-audio.mp3'
  new Notification("New music downloaded!");
});

self.addEventListener('backgroundcachefailure', function(event) {
  // ?
});
```

**Comment by wanderview** [comment]
> Edit: Not quite true. Cache.put will complete without a SW. Cache.add is essentially a fetch + cache.put so if the SW dies before the fetch completes then cache.put won't be called.

For posterity, gecko also treats Cache.add() as a service-worker-side fetch+put.  We hold the service worker alive until it completes, however.  This is largely due to implementation details, but also makes the developer experience more consistent.

I just wanted to note this as it may create different and unexpected behavior for people trying to figure out different service worker caching strategies.

**Comment by jakearchibald** [comment]
Moving to https://github.com/jakearchibald/background-cache
