### ISSUE TITLE
Should an IFRAME without src be controlled by SW when its parent is controlled?

### ISSUE THREAD

**Issue by kinu** [slightlyoff/ServiceWorker#612]
Currently when an IFRAME is created without src= it's not controlled by any SW, so opening a document inside the iframe and loading subresources by frame.contentDocument.write(...) isn't handled by SW either.

Per spec document.open() (and write()) does similar to 'navigation' but open and navigation are not really the same concept:
https://html.spec.whatwg.org/multipage/webappapis.html#dom-document-open
https://html.spec.whatwg.org/multipage/browsers.html#navigate

More specifically, should the following code show the same controller twice for the parent and iframe?

    <!doctype html>
    <iframe id=x></iframe>
    <script>
    var x = document.getElementById('x');
    console.log(navigator.serviceWorker.controller);  // <-- for parent doc
    console.log(x.contentWindow.navigator.serviceWorker.controller);  // for iframe
    </script>

Related chromium issue: https://code.google.com/p/chromium/issues/detail?id=439697

(As a side note: from implementor's pov making no-src iframe controlled by SW is not that straightforward)

**Comment by annevk** [comment]
In that case the `<iframe>` loads `about:blank`, which is not controlled. But that would indeed be confusing if that environment then starts fetching resources. I don't think we have carefully considered that case. (The same goes for `<iframe>` that fetches a data URL. Or a worker based on one.)

**Comment by treasonx** [comment]
Creating an iframe with `about:blank` is a commonly done when creating widgets that need script and style isolation from the host page. 

Since the widget needs to run in an wide variety of pages with various CSS styles and scripts. The script created iframe is a perfect solution for isolation. Rendering a widget UI within the iframe reduces the complexity involved in developing and maintaining thirdparty JS widgets. 

Since the iframe is on the same domain as the host page it can access the parent window's context and DOM. As a ServiceWorker implementor it feels like the worker would have the same visibility to assets being loaded in the frame as it does the host page. 

My use case allows users to add a service worker to their page by dropping in a script. It then has a slide out drawer UI which enables navigation between applications when the user is offline. I have a proof of concept implementation at [duskjs.com](http://www.duskjs.com).

**Comment by annevk** [comment]
Sure. The solution here is probably the same as it is for CSP et al, some kind of inheritance.

**Comment by jakearchibald** [comment]
Agree with @annevk that we should follow CSP here, which means using the document's controller if the iframe is `blob`, `data` etc https://w3c.github.io/webappsec/specs/content-security-policy/#globally-unique-identifier.

Does "globally unique identifier" include `about:` @mikewest?

@kinu sorry if this is a pain.

**Comment by mikewest** [comment]
We probably need to change the wording here to align with Fetch/URL. Does
"not a relative scheme" capture what we need here, @annevk?

**Comment by annevk** [comment]
What do we want to do for `ftp`? I think you want https://url.spec.whatwg.org/#is-local no?

**Comment by mikewest** [comment]
We do! Is that new?

**Comment by annevk** [comment]
Yes, you suggested it here: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26114#c4

**Comment by mikewest** [comment]
I did! Hooray for me. :)

Thanks for adding it to the spec. I'll see about fixing CSP, et al.
