### ISSUE TITLE
under what conditions should sandboxed iframes be intercepted?

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#648]
We've run across a question during implementation:

  Should sandboxed iframes be intercepted by the ServiceWorker?

Presumably this is only a question if the allow-same-origin exception is set on the iframe as well.  Otherwise the iframe is considered a separate origin.

Should we also require allow-scripts to be set in order for interception to occur?  It seems fetch event triggering a ServiceWorker is an implicit way to run scripts.

What does blink currently do here?

**Comment by wanderview** [comment]
We'll probably just not intercept sandboxed iframes at all in gecko for now.  We can relax this if there is some consensus on what is safe.

**Comment by ehsan** [comment]
Another interesting issue would be what to do with CacheStorage in such cases.  Both of the current implementation disable global.caches, Gecko by throwing an NS_ERROR_FAILURE internal error (ugh!) and Blink by throwing a SecurityError.  In my ideal world, the respective properties would just be hidden on the global in this case.

**Comment by mattto** [comment]
I think Blink currently intercepts the sandbox iframe, but not intercepting sounds like a good solution until a spec decision is reached. @slightlyoff @jakearchibald @metromoxie

**Comment by metromoxie** [comment]
The current Chrome behavior is almost certainly a bug, especially since I believe the interception happens even if the sandbox is not allow-same-origin, in which case it really should be treated as a separate origin. Offhand, @wanderview's initial suggestion makes a lot of sense to me, but not intercepting at all for now seems like the best path.

**Comment by jakearchibald** [comment]
Good catch. Sandboxed iframes without `allow-same-origin` shouldn't be intercepted.

I'm leaning towards no interception without `allow-scripts`, but I'd like to know more about the benefits of blocking script in an iframe, and if those benefits are lost by allowing a site's ServiceWorker to execute. @mikewest

**Comment by metromoxie** [comment]
@jakearchibald I don't think `allow-scripts` should be required for interception. `allow-same-origin` puts the script in the same origin, so it seems reasonable to me to allow a SW to deal with it.

The usual reason to restrict a sandbox iframe without `allow-scripts` is that untrusted code is going into the iframe, but it needs a combination of something like `allow-same-origin` and `allow-frames`, for example, so that it can create a login form to a same-origin service. However, you don't want to allow arbitrary untrusted JavaScript to execute in the origin, since it would have the capability of effectively XSS'ing your origin.

However, the point is that `allow-scripts` is meant to restrict the *content inside the iframe* from running scripts, since *those* are untrusted. However, the Service Worker is trusted code, so there's no reason it shouldn't be allowed to interact with content inside the iframe.

**Comment by jakearchibald** [comment]
Yeah, so only `allow-same-origin` should be required for SW interception within a sandboxed iframe.

@annevk @jungkees Am I right in thinking this is something that can only be fixed by the HTML spec? It should call fetch with the skip serviceworker flag. By the time the request gets to fetch, it doesn't know it came from a sandboxed iframe.

**Comment by wanderview** [comment]
Also, can we spec how the `caches` global works in sandboxed iframes?  The current blink-written WPT test expects self.caches to throw on access.  It seems more consistent with other specs for it to reject with SecurityError when you try to call a method on .caches.

**Comment by jakearchibald** [comment]
I'm closing this because I think it's part of the fetch/html integration. Reopen if I'm wrong @annevk
