### ISSUE TITLE
https should not be mandatory

### ISSUE THREAD

**Issue by tresdin** [slightlyoff/ServiceWorker#658]
Why is HTTPS madatory in Service Worker since Man in the Middle attacks can also be prevented by using WSS (WebSocket SSL) connection?

IMHO, HTTPS is never gonna be the future. Service Worker should provide an option for HTTP + WSS approaches instead of forcing developers to use HTTPS.

**Comment by jakearchibald** [comment]
I do not see how websockets solve this issue.

Dupe of https://github.com/slightlyoff/ServiceWorker/issues/274

**Comment by tresdin** [comment]
@jakearchibald Just send all sensitive data over wss. Then how can an attacker can steal the data?

**Comment by jakearchibald** [comment]
Web security isn't just about data the user sends you, it's also about the data you send your user.

Specifically, in this case, you'll be sending code that ensures user data is sent over a secure channel (this could simply be HTTPS, doesn't need to be wss), but you'll be sending that code over an insecure channel. That means a MITM simply needs to remove/rewrite the code that ensures the user data is sent securely.

**Comment by tresdin** [comment]
Your point makes a lot of sense. Your explanation help me a lot, indeed. Thank you.

**Comment by flaki** [comment]
Regarding our [twitter exchange](https://twitter.com/slsoftworks/status/581863309797924864) - as it turns out Firefox has its own method for easing debugging/development on non-trivial setups - those that require more than a static storage (ie. gh-pages).

Firefox uses the `dom.serviceWorkers.testing.enabled` setting - which, when set to true it disables the HTTPS-restriction on service workers completely (IIUC). One might argue that is too much of a vulnerability *(as leaving that setting open would make it so the browser is completely unprotected on all sites - practically removing all security provided by the feature in the first place)*.

One could also argue, that I should be filing this at Chromium dev (and that might be also true) however widespreed acceptance among big-league players could very much depend on solving the issue of integrating Service Worker development into current developer practices, so I think it might be useful to have at least guidelines in the spec for UA-s to ease development.

I would suggest, that a configuration setting (that would ship stable & developer versions alike) as the one above used in Firefox would solve the stated use cases (deliberately enabling testing on developer-owned devices), while requiring the **configuration value to be set to a domain name** (*only service workers located on said domain would be able to bypass HTTPS check*) would fix the problem of leaving one's device completely open for attacks on other sites.

This would effectively be an expansion on how browsers currently handle `localhost` as a special case — comments on this would be much welcome.

**Comment by KenjiBaheux** [comment]
@flaki we've been discussing about this over at http://crbug.com/441605 We are looking for interest (please star the bug) to prioritize it. Also, feel free to share more details about your use cases and thoughts about the approach [via Twitter](https://twitter.com/KenjiBaheux).

**Comment by flaki** [comment]
Cool! Thank you @KenjiBaheux, will make sure I chime in later!

**Comment by shmdhussain** [comment]
> Regarding our [twitter exchange](https://twitter.com/slsoftworks/status/581863309797924864) - as it turns out Firefox has its own method for easing debugging/development on non-trivial setups - those that require more than a static storage (ie. gh-pages).
> 
> Firefox uses the `dom.serviceWorkers.testing.enabled` setting - which, when set to true it disables the HTTPS-restriction on service workers completely (IIUC). One might argue that is too much of a vulnerability _(as leaving that setting open would make it so the browser is completely unprotected on all sites - practically removing all security provided by the feature in the first place)_.
> 
> One could also argue, that I should be filing this at Chromium dev (and that might be also true) however widespreed acceptance among big-league players could very much depend on solving the issue of integrating Service Worker development into current developer practices, so I think it might be useful to have at least guidelines in the spec for UA-s to ease development.
> 
> I would suggest, that a configuration setting (that would ship stable & developer versions alike) as the one above used in Firefox would solve the stated use cases (deliberately enabling testing on developer-owned devices), while requiring the **configuration value to be set to a domain name** (_only service workers located on said domain would be able to bypass HTTPS check_) would fix the problem of leaving one's device completely open for attacks on other sites.
> 
> This would effectively be an expansion on how browsers currently handle `localhost` as a special case — comments on this would be much welcome.

what about the android firefox browser, not able to go to about:config and change the setting there? second point is how can we debug the service worker script for mobile firefox, for desktop we could do about:debugging#workers?
