### ISSUE TITLE
self.caches should spec what to do for "untrusted" origins

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#687]
Currently `self.caches` is spec'd to always return a CacheStorage object.  Clearly, there are cases where this should not be done.  For example, in a context with a synthetic origin such as a sandboxed iframe or data URI worker.  The spec does not say what to do in these cases.

The web-platform-tests from blink show that the blink implementation throws SecurityError in this case.  That seems reasonable.

I believe @ehsan would prefer we just hide the `self.caches` property in these cases.

Thoughts?

@jakearchibald @slightlyoff @jungkees @annevk

**Comment by ehsan** [comment]
> I believe @ehsan would prefer we just hide the self.caches property in these cases.

@wanderview is speaking the truth!

**Comment by ehsan** [comment]
(alongside the global Cache and CacheStorage interface objects of course)

**Comment by inexorabletash** [comment]
FWIW, in Chrome we still expose the globals, but `self.caches` throws a `SecurityError` on access with details about why the access was denied. This is consistent with what we do for  `window.sessionStorage`, `window.localStorage`.

For Indexed DB we instead throw on access to the `open()`/`deleteDatabase()` methods hanging off the `indexedDB` global.

**Comment by annevk** [comment]
I think rejecting `self.caches.open()` makes slightly more sense. Getters that can throw are bad and hiding the API is not a pattern we normally follow (and would likely break going forward as people start to assume it is there).

**Comment by wanderview** [comment]
I recently changed gecko to reject the promise with SecurityError.

Our bindings code would actually make it hard to throw instead of reject the promise.  It automatically converts errors to a promise rejection for methods that return Promise<> in their webidl.

**Comment by domenic** [comment]
> Our bindings code would actually make it hard to throw instead of reject the promise.

As it should \o/

**Comment by jungkees** [comment]
So I think the way to go is like rejecting with a SecurityError exception when the service worker client's origin is a synthetic origin like a sandboxed iframe or data URI worker.

I'm thinking of adding this step:
If the incumbent settings object's origin is not a scheme/host/port tuple, then return a promise rejected with a SecurityError exception.

Do we have any better reference concept that better grabs "untrusted" origins for this case?
/cc @annevk @mikewest

**Comment by annevk** [comment]
I think you just want to use the origin of the global object's settings object. And the "is not a scheme/host/tuple" thing makes little sense. Just make sure it's not a unique identifier.

**Comment by jungkees** [comment]
Addressed: c748d9892317bf1fa4631db8d7c88a60577ad26f. Thanks @annevk. I think we should use the incumbent settings object for the security origin check. And all the methods on CacheStorage need this guard as the _name to cache map_ internal slot should not exist for such case in the first place.

**Comment by annevk** [comment]
@bzbarsky has been trying to convince me to use the global object rather than the incumbent settings object, actually. Why do you think you should use the incumbent setings object here?

**Comment by jungkees** [comment]
I think [this example](https://html.spec.whatwg.org/multipage/webappapis.html#incumbent-settings-object) explains. So in our case here:

```js
<!-- a/a.html -->
<iframe src="b.html"></iframe>
<script>
var subframe = document.getElementsByTagName("iframe")[0];
subframe.contentWindow.caches.open(name);
</script>
```
the origin check should be done against the subframe's global object rather than the callingframe's one. Am I misunderstanding?

Curious to know what you've discussed with @bzbarsky. Do you have any pointer?

**Comment by bzbarsky** [comment]
In the case you're describing, the incumbent settings object is identical to the entry settings object and both are settings objects for `a.html`.  It sounds to me like you're a bit confused on that point...  Note that your example is subtly different from the one you link to in the spec, in that in your example there is no script running inside `b.html` at all, yes?

The intuitive understanding of incumbent vs entry settings objects is this: entry settings is where script was entered; incumbent settings is what script was running when the call into the DOM API was made.

Back to the issue in question here... what assumptions are you willing to make in terms of what objects can touch each other and how origins work?  Generally, if we managed to make the call at all that means the effective script origins of all the stuff involved are the same (or were the same at some point in time, for browsers that don't revoke things).  Since `document.domain` can't affect whether something is a unique identifier origin (so far?) that means that you really can use any of the four origins involved here (entry settings, incumbent settings, current realm (aka callee function), this object) and the effect will probably be the same.  Emphasis on _probably_.  If you have a clear mental model of which of those 4 origins is actually relevant here, you should use that one.  Which brings us back to the question of what origin is actually used for the operation that can't be performed when that origin is a unique identifier.  How is _that_ defined right now?

**Comment by jungkees** [comment]
I believe you pointed accessing to an off-origin iframe's objects from the calling frame will not be possible in the first place, and in this case neither can we manipulate the effective script origin as the origin is a unique identifier origin.

> what origin is actually used for the operation that can't be performed when that origin is a unique identifier

The operation we discuss to be not allowed against a unique identifier origin is accessing to the [_name to cache map_](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#dfn-name-to-cache-map) internal slot which is defined as a per-origin cache storage. And as in [the previous comment ](https://github.com/slightlyoff/ServiceWorker/issues/687#issuecomment-96516567) in the thread, we're trying to make the methods (`self.caches.open(name)`, etc.) on the `CacheStorage` return a rejected promise instead of making the getter of the `CacheStorage` object (`self.caches`) itself throws.

As per your comment, I think using entry settings object here makes sense.

**Comment by bzbarsky** [comment]
> As per your comment, I think using entry settings object here makes sense.

OK, that flat out contradicts your comments in https://github.com/slightlyoff/ServiceWorker/issues/687#issuecomment-97752545

Also, my comments about not being able to change effective script origin on unique identifiers apply if the only decision is a boolean "is this a unique identifier origin?".  If you actually care about the identity of the origin, then you need to care about the identity of the origin!

Let's look at this testcase, which has full generality, I believe:

    
    <iframe src="b.html"></iframe>
    <iframe src="c.html"></iframe>
    <iframe src="d.html"></iframe>
    <script>
    window.onload = function() {
        window.frames[0].doOpen();
    }
   </script>

    
    <script>
    function doOpen() {
      parent.frames[1].caches.open.call(parent.frames[2].caches, someName);
    }
    </script>

Let's say a.html, b.html, c.html, d.html are all from different origins but have all set their document.domain so that they are same-effective-origin, so that the doOpen() call succeeds, as does the caches.open call.  Which origin should be used for the name-to-cache map?  The options are the origins of  a.html, b.html, c.html, and d.html.  The entry settings object is a.html, incumbent settings is b.html, the callee Realm is c.html, and the this object is from d.html. 

Another option to sidestep all this is to spec that the ServiceWorker APIs fail out if `document.domain` was set and that setting `document.domain` throws if the ServiceWorker APIs were accessed, so you can't do both in the same document.  There's been some talk of doing that for some other APIs but it's never materialized...

**Comment by jungkees** [comment]
We defer it to WebAppSec meeting tomorrow (in TPAC).

**Comment by jakearchibald** [comment]
F2F: update spec. Property won't exist in non-secure contexts
