### ISSUE TITLE
Does a SW control a page outside its scope reached by a redirect?

### ISSUE THREAD

**Issue by mattto** [slightlyoff/ServiceWorker#706]
Suppose URL `A` is in a SW's scope. The browser navigates to `A` which returns an HTTP 302 redirect to URL `B` outside the SW's scope. Does the SW control the page?

I think it should not control the page, and I'm wondering if this is covered by the spec?

**Comment by mattto** [comment]
Tracked in http://crbug.com/495384

**Comment by jungkees** [comment]
If URL `A` is in the SW's scope, Fetch will call Handle Fetch with the request upon navigating to that URL. So it's the SW that returns the response to Fetch. Do you have this in mind like the SW returns a custom response with 302? If this happens Fetch will call Handle Fetch again with the redirect URL (`B` in this example) so the Handle Fetch will try the Match Service Worker for that request.

**Comment by mattto** [comment]
I guess there's a few cases:
- The SW does event.respondsWith(new Response(302))
- The SW does event.respondWith(fetch('url-that-redirects'))
- The SW does nothing, the server responds with HTTP 302

**Comment by jungkees** [comment]
In any case above, Fetch does not follow the redirect (as the original request sets the redirect mode to manual - [navigate step 15](https://html.spec.whatwg.org/#navigate)). So when the navigation algorithm got the redirect, it either fetch the target URL of the redirect again or abort (if the URL is off-origin.)

In the case Fetch calls the Handle Fetch with the request for the redirect URL, it tries to match SWR again. I think if it matches any, that client should be controlled by the matched SW.

**Comment by jakearchibald** [comment]
> The SW does `event.respondsWith(new Response(302))`

I assume you mean: `event.respondWith(Response.redirect(url))`? In this case the fetch algorithm receives the redirect response, and (as @jungkees says) because the request's "redirect mode" flag is not "follow", the redirect response is passed back to the navigation algorithm. `url` will be loaded as a navigation, using the ServiceWorker associated with the destination `url`, if any. The url in the location bar will be the final destination url.

> The SW does `event.respondWith(fetch('url-that-redirects'))`

In this case, `fetch()` will swallow the redirects, so you'll end up with a non-3xx response. That response is passed back to the page's invocation of the fetch algorithm. If it was a client request, and the response was not "basic" or "default" (eg, if it was from another origin), it will be treated as a network error. Otherwise, the page will load the response as if it came from the origin request url, and it will be controlled by the SW that provided the response, the url in the location bar will not change.

> The SW does nothing, the server responds with HTTP 302

The navigation algorithm will receive the redirect response and issue a new fetch for the destination url, using the ServiceWorker associated with the destination url, if any. The url in the location bar will be updated to reflect the destination url.

I'm pretty sure the spec is ok here.

**Comment by mattto** [comment]
@jakearchibald  Thanks for the explanations. Just want to be sure Chrome is doing this right. I have a question about the same-origin, ``event.respondWith(fetch('url-that-redirects'))`` case. What happens in this case:

* SW a.js
```javascript
// controls scope '/A/'
onfetch = function(e) {
  if (e.request.url.indexOf('redirect') != -1) {
    e.respondWith(fetch('/http-302'));
  }
}
```

* SW b.js
```javascript
// controls scope '/B/'
onfetch = function(e) {
  e.respondWith(new Response('hello from SW B'));
}
```

* The server responds to ``/http-302`` with HTTP 302 to ``B/hello``
* Otherwise, if no SW intercepts a request, the server responds with ``hello from server``.

You navigate to ``A/redirect``. I get that the URL in the location bar would be ``A/redirect``, and the controller would be ``a.js``. Is the document content ``hello from SW B`` or ``hello from server``?

Current Chrome is from server.

**Comment by annevk** [comment]
It should be from server. `fetch()` within an SW does not roundtrip through another SW.
