### ISSUE TITLE
Introduce `Service-Worker-Max-Age` header

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#721]
@ehsan, please correct me if this didn't match what we discussed.

Since service workers use byte-for-byte comparison rather than HTTP cache semantics, there's a risk that when using a service worker library, it becomes harder to update, since you need to change the library code.

So it would be good that in addition to the byte-for-byte comparison, there's also a header that indicates when the browser should start ignoring the service worker being byte-for-byte identical.

**Comment by ehsan** [comment]
That sounds like an accurate summary!

**Comment by annevk** [comment]
The max-age is counted since installation.

**Comment by slightlyoff** [comment]
There's pretty strong consensus from the F2F that this is worth doing in M2 (IIRC). Marking as such.

**Comment by delapuente** [comment]
The are two perspectives here. One option is to extend byte-to-byte comparison to the whole imported scripts (`importScripts`) graph. If one node has change, update. The other is related with #839. The header `Service-Worker-Force-Update` proposed by @jakearchibald can be enough for this but it's hard to automatically calculate in the server cause it involves to calculate the import graph there.

**Comment by collimarco** [comment]
> One option is to extend byte-to-byte comparison to the whole imported scripts (importScripts) graph.

+1 for this

**Personally I don't like the idea of having to return a custom header** to force the refresh of the imported scripts. 

This is because at Pushpad (which is a BaaS) we have a script that is imported in our customers' service workers. When we update our script we want the update to be propagated. However **we cannot ask our customers to return custom headers for their service worker (some of them for example have simple websites or blogs powered by Wordpress)**.

I have described more extensively about our situation and why we need automatic updates of the imported scripts in [this blog post](http://blog.pushpad.xyz/2016/07/service-worker-importscripts-never-updates-scripts/).

**Comment by jakearchibald** [comment]
We're going to check imported scripts by default https://github.com/slightlyoff/ServiceWorker/issues/839#issuecomment-236256162
