### ISSUE TITLE
Make the Cache API deal with request's redirect mode not being "follow"

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#737]
I think it would make sense for the Cache API to take request's redirect mode into account. Currently the Cache API always returns the redirected response. IT would make sense that when redirect mode is not "follow", you'd get an error instead.

See also https://github.com/whatwg/fetch/issues/79.

**Comment by wanderview** [comment]
If we do this, how can a site offline a navigation that redirects to a cross-origin resource without CORS headers?

1. `cache.add(redirectingNavUrl, { mode: 'cors', redirect: 'follow' })` fails because redirect does not have CORS header.
2. `cache.add(redirectingNavUrl, { mode: 'no-cors', redirect: 'follow' })` succeeds, but the resulting opaque result cannot be passed to `respondWith()` for a navigation.

Today, however, you can offline the original site during install and offline the cross-origin redirect destination using a read-through-cache approach.  You can do:

* `cache.add(redirectingNavUrl, { mode: 'same-origin', redirect: 'manual' })` to store the opaqueredirect.
* The navigation will then follow the redirect and get another service worker for the cross-origin destination.  (This doesn't happen in the cases above because skip-serviceworker-flag.)
* That other service worker can offline the final destination.

If we can't store the `opaqueredirect` in Cache, though, then the original site always has to go to network which will fail while offline.

**Comment by jakearchibald** [comment]
We should be able to store opaque redirects, and we don't say you can't so it should be fine.

**Comment by jakearchibald** [comment]
F2F resolution: `cache.match(request)` should reject if the redirect mode is manual and the matched response had a redirect.

**Comment by annevk** [comment]
To be clear, the resolution was to fix both of those in Fetch.

**Comment by annevk** [comment]
Having said that, the Cache API needs to be updated to store response's url list to make this work. So that does need to be updated as part of this.

**Comment by wanderview** [comment]
> Having said that, the Cache API needs to be updated to store response's url list to make this work. So that does need to be updated as part of this.

I think the spec does this already, but it wasn't previously exposed to script in any way.  So the URL list or equivalent needs to be added to implementations.
