### ISSUE TITLE
Should ServiceWorker.scriptURL have fragment removed?

### ISSUE THREAD

**Issue by nikhilm** [slightlyoff/ServiceWorker#742]
I can't find anything in the spec that has "exclude fragment flag set" for scriptURL, only for scope. But the web-platform-test suggests otherwise. test 2 at https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/LayoutTests/http/tests/serviceworker/serviceworkerobject-scripturl.html

Which one is canonical? For now I'm going to assume fragments are allowed in scriptURLs.

**Comment by jakearchibald** [comment]
Seems like https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#register-algorithm doesn't strip the fragment before it does a comparrison. That leads me to think scriptURL should include fragments.

What do you think @jungkees?

**Comment by jungkees** [comment]
Currently, it doesn't strip the fragment for scriptURL, and the scriptURL comparison is in two places: one in the Register algorithm (step 4.2.2) and the other in Update algorithm (step 4.25). This means, tweaking the fragment part of the url makes it get through to Install phase (possibly checking the network) for the same javascript file as putting a different query string does. If this case is desirable and handy to devs, we may want to keep it as-is. Otherwise, excluding the fragment for scriptURL makes sense to me.

In either case, I think we need to change the Update algorithm step 4.25 to not use the fragment in the url comparison. Otherwise, the user agent continues to install the byte-for-byte matching script resource, which is meaningless.

**Comment by annevk** [comment]
If you want to compare URLs, please use https://url.spec.whatwg.org/#url-equivalence. If that doesn't provide something you need, please file an issue. We should have consistent URL comparison across the platform.

**Comment by jungkees** [comment]
I think that would work. The discussion here is whether to set the _exclude fragments flag_ for scriptURL comparisons. I'll add xrefs to https://url.spec.whatwg.org/#url-equivalence when updating the text with a decision.

In reflection, I don't think we have to strip the fragment of the scriptURL passed to `register()` method as it's part of the url (so we don't want to special case it), meaning the register attempt will have a chance to get through to update. And there in the update phase, if the script resource has not been changed we won't install the same resource again for which we have to set the _exclude fragments flag_ (Update step 4.25). Thoughts?

**Comment by annevk** [comment]
Sounds reasonable.

**Comment by wanderview** [comment]
Gecko bug to change update behavior: https://bugzilla.mozilla.org/show_bug.cgi?id=1201498

**Comment by cdumez** [comment]
The stripping of the fragment identifier is covered by service-workers/service-worker/serviceworkerobject-scripturl.https.html. This test passes in both Firefox and Chrome but fails in WebKit.

**Comment by jungkees** [comment]
Let's track this in https://github.com/w3c/ServiceWorker/issues/1249#issuecomment-352182516.
