### ISSUE TITLE
WindowClient.navigate() for the same origin but off-scope clients

### ISSUE THREAD

**Issue by jungkees** [slightlyoff/ServiceWorker#752]
@romandev asked this question while implementing `navigate()` in Blink.

The spec currently disallows navigate() for off-scope clients. (See [navigate(url) step 4](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#client-navigate))

E.g. a SW can get an off-scope client by
 - `clients.matchAll({ includeUncontrolled: true })`
 - `client.navigate(to-off-scope-url).then(off-scope-client => { off-scope-client.navigate(url); })`

And those reject with a TypeError. Was it intended? Should we allow the same origin but off-scope clients to navigate?

**Comment by wanderview** [comment]
I thought scopes were added to kind of allow multi-user environments and limit the damage from XSS.  It seems letting navigate() operate outside the scope would be counter to those goals.

**Comment by johnmellor** [comment]
It seems `clients.matchAll({ includeUncontrolled: true })` combined with navigation of off-scope clients would allow a https://www.stanford.edu/~username/ tab to navigate another independent https://www.stanford.edu/ tab to a spoof URL, which isn't otherwise possible.

This seems like a general problem with off-scope WindowClients though, not one specific to navigate().

Perhaps you should only be able to access WindowClients that match the `maxScopeString` defined by the [Update algorithm](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#update-algorithm) (even if you pass `includeUncontrolled:true` to `matchAll`).

@jakearchibald

**Comment by jungkees** [comment]
F2F: Getting same origin off-scope clients and using navigat() on them should be allowed.

**Comment by johnmellor** [comment]
This would also make XSS more powerful. Imagine an attacker that installs a Service Worker by exploiting a JSONP endpoint at `https://www.google.com/calendar/api/events?callback=XSS_HERE` (as discussed at https://crbug.com/422966). The `maxScopeString` of such a Service Worker is `/calendar/api/`, so it cannot intercept fetches outside that path, but granting it the ability to navigate off-scope clients would allow attacks like the following:
- User opens a new https://www.google.com/ tab.
- Malicious Calendar SW navigates this off-scope tab to https://www.google.com/calendar/api/foo, so that it becomes on-scope.
- Malicious Calendar SW spoofs the Google homepage, and uses `history.replaceState()` to change the apparent URL of the spoofed homepage (displayed in the location bar) to "https://www.google.com/".
- This attack is likely impossible for the user to detect without inspecting the HTML source.

Did the F2F discuss such risks?

**Comment by jakearchibald** [comment]
This case wasn't considered, but is worth considering

**Comment by jungkees** [comment]
Yes, we missed that scenario. The rationale why we decided to return all the client in the origin was https://github.com/slightlyoff/ServiceWorker/issues/428#issuecomment-53413333. However, returning all the clients in the origin **under `maxScopeString`** would make sense to avoid the outlined threat.

> Perhaps you should only be able to access WindowClients that match the maxScopeString defined by the Update algorithm (even if you pass includeUncontrolled:true to matchAll).

**Comment by jakearchibald** [comment]
> Perhaps you should only be able to access WindowClients that match the maxScopeString defined by the Update algorithm (even if you pass includeUncontrolled:true to matchAll).

This sounds fine to me, we can open it out later.

**Comment by jungkees** [comment]
In reflection, I think we should stay with the current `.navigate()` as-is. (i.e. not allowing navigations of off-scope clients regardless what maxScope was set).

Suppose setting a maxScope in the header to `https://www.stanford.edu/` but setting the effective scope to `https://www.stanford.edu/~username/`. Then, `matchAll({ includeUncontrolled:true })` will still return a client with `https://www.stanford.edu/`. Navigation of that client should NOT be allowed, right?

Also, returning all the clients in the origin from `matchAll({ includeUncontrolled:true })` and rejecting on the actual operations on off-scope clients sound more reasonable to me. (due to the reason here: https://github.com/slightlyoff/ServiceWorker/issues/428#issuecomment-53413333)

`.navigate()` currently does so. WDYT?

(Note that `.focus()` and `.postMessage()` are NOT filtering off-scope clients now. Is that what we wanted?)

**Comment by jungkees** [comment]
One last thing for now. The current `.navigate()` step 4 disallows the navigation of in-scope-but-not-controlled clients (shift+reload of in-scope client, etc.) as well as off-scope clients. If this is okay, I'll close the issue. It seems Chrome is ready with the implementation of the current spec: https://code.google.com/p/chromium/issues/detail?id=500911.

/cc @jakearchibald @johnmellor

**Comment by mattto** [comment]
I'm OK with implementing the most restrictive thing and loosening restrictions later if needed. In-scope-but-not-controlled seems like a rare edge case that doesn't need to block shipping.

**Comment by jungkees** [comment]
Agreed. Closing.
