### ISSUE TITLE
what should the document base URI for an intercepted navigation

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#787]
Now that the spec says to propagate back the intercepted Response.url, but its careful not to change the URL shown in the window's URL bar for a navigation.

What should the base URI of a document be in this case, though?  The original URI or the intercepted Response.url?  What about window.location?

@annevk @jakearchibald

**Comment by annevk** [comment]
All should be the requested URL. Basically the response URL is not used.

**Comment by bzbarsky** [comment]
So this is different from the behavior for stylesheets, where the response URL becomes the base URL, right?  Why the difference?  That is, why does whatever logic required the base URL to be the response URL for stylesheets not apply to documents?

**Comment by wanderview** [comment]
It is a bit weird that the baseURI doesn't change.  This means you can't build a separate site with relative resource paths under /offline/ and then return it for the navigation.  Because all those relative resources will load using the original request URL as the base and be broken.

**Comment by annevk** [comment]
For stylesheets the response URL becomes the URL (as if there was a redirect). We don't want that for navigation however. A resource served from the cache shouldn't change the URL in the address bar and such. @jakearchibald can explain more if needed or maybe dig up a pointer to the meeting where we discussed this.

**Comment by wanderview** [comment]
I agree we talked about the address bar not changing, but not changing the baseURI actually seems counter to what we would want for @jakearchibald's use case.  It would mean you could not use relative resources in the html Response used to intercept the navigation.

**Comment by bzbarsky** [comment]
> For stylesheets the response URL becomes the URL (as if there was a redirect)

Becomes the URL in what sense?

Let's ignore service workers for now and just consider basic HTTP redirects.  Consider a load for a stylesheet that starts with `<link rel="stylesheet" href="A">` where `A` then redirects to `B`.

The resulting `StyleSheet` object has `A` as its `.href` but uses `B` as its base URL.  See http://web.mit.edu/bzbarsky/www/testcases/css-loading/test-redirect-1.html for a simple testcase.

The first part of that is kinda specced at https://drafts.csswg.org/cssom/#concept-css-style-sheet-location and I'm not sure whether the second part is specced anywhere obvious.

But the point is that stylesheets have two URLs associated with them: one that they expose as their `.href` and another that they use as the base URL.  I assume in the service worker case `response.url` affects the latter but not the former, right?

**Comment by bzbarsky** [comment]
Similar thing for scripts, by the way.  Last I checked, the location of a script as it shows up in error stacks or whatnot is the original URL the fetch started with (presumably not affected by response.url in the service worker case), but the location used for muting decisions is the post-redirect URL (and hence presumable affected by response.url).  Base URLs are not an issue there, since scripts don't have one, of course, so it's not directly relevant to our discussion here.

**Comment by annevk** [comment]
You are correct, `.href` is not affected.

Interesting point about scripts. I guess in both cases we don't want to expose redirects to cross-origin URLs though in the stylesheet scenario that would end up with a non-accessible stylesheet anyway (CSSOM-wise).

**Comment by bzbarsky** [comment]
I guess my point was that we could/should decouple "base URL" from "URL" for documents in the interception case.

Note that this sort of thing already happens at least for `about:blank` (which inherits its base URI along with its origin, iirc).

**Comment by annevk** [comment]
Interesting precedent, loading `<iframe onload=w(this.contentDocument.baseURI);w(this.contentWindow.location)></iframe>` in the Live DOM viewer does indeed show that to be true. @jakearchibald, what do you think?

**Comment by bzbarsky** [comment]
> this.contentDocument.baseURI

You have to be careful with this one, because WebKit and Blink totally lie in that getter: they return a string that has nothing to do with the actual base URI they use.  See https://code.google.com/p/chromium/issues/detail?id=484930 and https://bugs.webkit.org/show_bug.cgi?id=144652 (which include links to and pastes of code that tests the actual base URI they use).

But yes, the upshot is that the base URI of `about:blank` is inherited.

**Comment by jakearchibald** [comment]
F2F: Ask developers via a blog post. & see if we can safely make this change anyway. Showing both CSS & document and asking where links & background images would go. Send it around the group before publishing.

**Comment by slightlyoff** [comment]
From the F2F discussion I'd like to capture a few options:

 - regardless of which way we decide this, we can extend `Request`s from pages with extra content about the base URL, which would allow a SW to handle these sub requests however it likes
 - we can do this for both CSS and main-document-generated fetches, allowing us to more easily adopt a single policy for both (which I know @ehsan favors)
 - we can extend the `Response` constructor to allow a base to be specified, bringing synthetic responses in line with `fetch()`'d responses.

**Comment by annevk** [comment]
Throughout the platform we consistently use the URL from the response as the base URL, even though we might use the (potentially different) request URL for some other purpose. Since that is currently an invariant we consistently offer, I think we should continue to do so by default. We could perhaps offer further overrides, but I'm not entirely swayed it's needed.

**Comment by jakearchibald** [comment]
Summary from https://jakearchibald.com/2016/service-workers-and-base-uris/:

[[1](https://jakearchibald.com/2016/service-workers-and-base-uris/#comment-2505916613)] - `event.respondWith(fetch(event.request))` should preserve regular browser behaviour. Base url should come from the request url. (This is contradictory, the impression is you'd use redirects to set the base url, which doesn't really work in our current system).

[[2](https://jakearchibald.com/2016/service-workers-and-base-uris/#comment-2497710055)] - use the response url for the base (I think, it's not clear when it comes to pages).

[[3](https://jakearchibald.com/2016/service-workers-and-base-uris/#comment-2497418932)] - use the request url (but mistakingly assumes this is normal browser behaviour).

[[4](https://jakearchibald.com/2016/service-workers-and-base-uris/#comment-2496751161)] - allow setting of base [via header](http://tools.ietf.org/html/rfc2068#section-14.11).

[[5](https://jakearchibald.com/2016/service-workers-and-base-uris/#comment-2494770286)] - use the response url

[[6](https://jakearchibald.com/2016/service-workers-and-base-uris/#comment-2496192942)] [[7](https://jakearchibald.com/2016/service-workers-and-base-uris/#comment-2496404752)] [[10](https://jakearchibald.com/2016/service-workers-and-base-uris/#comment-2496426381)] - response url for CSS, request url for pages.

[[8](https://jakearchibald.com/2016/service-workers-and-base-uris/#comment-2493205529)] [[9](https://jakearchibald.com/2016/service-workers-and-base-uris/#comment-2493131602)] [[11](https://jakearchibald.com/2016/service-workers-and-base-uris/#comment-2492078834)] [[12](https://jakearchibald.com/2016/service-workers-and-base-uris/#comment-2491980695)] - use the request url, happy to break `event.respondWith(fetch(event.request))`

**Comment by jakearchibald** [comment]
Unfortunately I don't think the answers were particularly useful, there's a lot of confusion around when `fetch()` would return a redirect and when it wouldn't.

Some developers are happy for the SW to act like a server, where it'd swallow redirect or deliberately serve redirects, but this can't work due to the security stuff around opaque redirects.

Despite some developers being happy with `event.respondWith(fetch(event.request))` breaking non-SW behaviour, I'm pretty sure it'll create angst if people try and use SW just to create offline fallback pages, and find that `event.respondWith(fetch(event.request).catch(…))` is causing difficult-to-debug differences. This was a mistake of appcache that I'm really against introducing.

Seems that whatever we pick here is going to be what a large number of developers do not expect, so for consistency reasons I'm happy to go for response url across the board, but a way to change it via a header or property on `response` (maybe just `response.url`?) would be nice.

**Comment by annevk** [comment]
I don't think we should allow setting response.url. We want that to be reliable for security checks. Responses could have a baseURL field perhaps, but I'd prefer we introduce that at the moment we identify a need.

**Comment by wanderview** [comment]
Having a convenience method to convert a response to a synthetic response would allow someone to opt in to the request url.  Something like `response.asSyntheticResponse()`.

Of course, that would not work for opaque responses, though.

**Comment by annevk** [comment]
Opaque responses are another good reason to not let the service worker change the base URL.

**Comment by jakearchibald** [comment]
F2F: Use `response.url` as the base.

TODO: Investigate if this breaks anything.

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1222008

**Comment by jungkees** [comment]
I believe https://github.com/whatwg/fetch/pull/146 addressed the f2f resolution. If more things are left with this issue, feel free to reopen it.

Closing.
