### ISSUE TITLE
The "uninstalling flag" check in ServiceWorkerRegistration.update() should be moved to the Update algorithm

### ISSUE THREAD

**Issue by ehsan** [slightlyoff/ServiceWorker#807]
Currently the spec in section 3.2.5 step 3 says:

```
If registration's uninstalling flag is set, reject p with an "InvalidStateError" exception and abort these steps.
```

Therefore, if the script calls unregister() and update() sequentially, assuming the job queue is not empty, the Unregister algorithm runs after the initial call to update(), which is where we check the uninstalling flag.

It seems better to move this check to the Update algorithm instead so that we can check the latest value of the uninstalling flag no matter what the order of operations leading to this have been.

I'm modifying Gecko to implement this.

**Comment by wanderview** [comment]
I also think it makes sense in the update algorithm.  This will also abort soft updates that are triggered on an uninstalling registration.

**Comment by jungkees** [comment]
Added the guard in Update algorithm: 784f69a8fdd027b267abf8f0d80b5c40df137a7a. I didn't remove the corresponding steps in update() and Soft Update so they can abort the update requests before scheduling them. Do you think we better remove them?

**Comment by wanderview** [comment]
I think it would be better to remove the additional checks in update() and Soft Update.

Consider:

1) Registration has its uninstalling flag set.
2) A new register job is pending in the queue.  This will clear the uninstalling flag when it runs.
3) update() is called

Leaving the checks in place will cause the update() call here to be racey.  If update() is called before the register job runs, then it will abort.  If its called after the register job is run then the update will be executed.

In contrast, if we remove the synchronous uninstalling flag checks, then we always get the same behavior.  The update job always execute because the register job clears the flag.

**Comment by jungkees** [comment]
Agreed. Remove those additional checks: 23e6438ae3e2678b7030bc8d6d8778f1b05dc19d. Thanks!
