### ISSUE TITLE
What is FetchEvent.clientId for navigation requests

### ISSUE THREAD

**Issue by mattto** [slightlyoff/ServiceWorker#808]
Spin-off of issue #723 

The spec recently made clientId == null for navigation requests:
https://github.com/slightlyoff/ServiceWorker/commit/872e51b9f06d9872d925a2877f02ca765194ef78

But if I'm not mistaken, Gecko populates clientId[1] on the navigation request and re-uses it for subresource requests from that client:
```
79       .then(function() { return with_iframe(scope); })
80       .then(function(f) {
81           frame = f;
82           assert_equals(
83             frame.contentDocument.body.textContent.substr(0, 15),
84             'Client ID Found',
85             'Service Worker should respond to fetch with a client id');
86           initial_client_id = frame.contentDocument.body.textContent.substr(17);
```
[1] http://lxr.mozilla.org/mozilla-central/source/testing/web-platform/mozilla/tests/service-workers/service-worker/fetch-event.https.html?force=1

What is the desired behavior? cc @jungkees @wanderview

**Comment by jungkees** [comment]
I remember we chatted about this about a month ago, and @wanderview was happy with undefined for navigation at least for now. (I did it with null as we need some IDL support for undefined.)

Meanwhile, it seems Gecko implemented `.clientId` for a navigation request to set the value to the id of a newly created (target) client.

I was a bit not comfortable with setting it to the target client's id instead of that of the source client. I'm happy to set it to the target client's id if it makes sense to others and useful to devs. WDYT?

**Comment by jungkees** [comment]
cc @jakearchibald @annevk @slightlyoff

**Comment by annevk** [comment]
The  target makes somewhat more sense than the source, though in specification theory the target might not have been created yet so how exactly that setup should work is a tad unclear. It can work, but it requires a lot of refactoring of "navigate", which is already a bit of a mess. I'm worried that once we untangle it more, we might find some problems with the stuff we are now building on top of it.

**Comment by wanderview** [comment]
I think it should be undefined or null for now.  It cannot be the target id because it does not exist, and may never exist depending on what the service worker does.  I think this is a bug in gecko.

**Comment by wanderview** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1236933

**Comment by wanderview** [comment]
For reference, here is the IRC conversation that sparked this change:

  http://logs.glob.uno/?c=freenode%23whatwg&s=11+Nov+2015&e=11+Nov+2015&h=clientId#c974050

**Comment by wanderview** [comment]
I guess @ehsan doesn't agree with me.  He'd prefer to show the target clientId.  I've asked him to comment here so we can discuss.

**Comment by wanderview** [comment]
I think @ehsan implemented something that I am ok with, though.  You can get a clientId for a navigation FetchEvent, but the clients.get(evt.clientId) returns null.  The client does become "live" until the navigation successfully completes.

**Comment by ehsan** [comment]
I implemented FetchEvent.clientId based on the previous text of the spec, and I think the implementation is pretty straightforward.  Here is what I understood from the previous text of the spec:

FetchEvent.clientId should be set to the ID corresponding to the client that the document being navigated to represents.  In Gecko, the implementation works by computing a client ID on something close to our notion of clients settings object as the navigation is starting and passing that to the non-subresource FetchEvent that is going to be dispatched.  If the navigation finishes successfully, we use the computed client ID as the client ID for the respective client.

The reason why I disagree with this spec change is that if a developer actually needs the clientId for the top-level document, we're making them go through unnecessary hoops, since this change will force them to get the clientId out of a subsequent fetch and/or Clients.matchAll(), in both cases they'd have to solve the problem of how to verify the clientId that they get actually belongs to the document they have observed a FetchEvent for before.

A number of objections raised in the Mozilla bug and my response to them:

* What if the document doesn't get created, for example in the case of a network error?
** Then the client ID will never end up getting used, and doing things such as postMessage() to it won't work, exactly like a client ID belonging to a document that has been destroyed since the author obtained it.
* What if you clicked a link on a source document to trigger the navigation and/or opened the page from a homescreen icon and such?
** That doesn't matter since the clientId doesn't represent the navigated from document.
* What about cross origin non-subresource fetches?
** They won't get intercepted, so that is moot.
* What if the navigated to document ends up being controlled by another service worker?
** That's OK too, since you can already get that clientId through includeUncontrolled.

**Comment by jakearchibald** [comment]
> The reason why I disagree with this spec change is that if a developer actually needs the clientId for the top-level document, we're making them go through unnecessary hoops, since this change will force them to get the clientId out of a subsequent fetch and/or Clients.matchAll()

On the other hand, the Mozilla behaviour makes it really tricky to know when a client has gone. With the current spec, `clients.get(clientId)` returning null means the client has gone, so its data can be removed from databases etc. In the Mozilla behaviour, if null is returned the client may have expired, isn't yet created, or may never be created. I'm a little worried about this.

Maybe we should have a new property for what Mozilla does now? Something like `reservedClientId` or `potentialClientId`? This would be handy during navigations, as you get to link together the origin client and the new client.

**Comment by jungkees** [comment]
Yes, I agree. How about keeping the current spec behavior (returning undefined/null) and discussing whether to add .potentialClientId in this f2f?

**Comment by ehsan** [comment]
Exposing this under a different attribute is fine by me.  I'll modify Gecko to return null for now, and we can add the other attribute depending on the f2f discussion.

**Comment by jungkees** [comment]
Great. Thanks. I'll close the issue after filing a new one for potentialClientId.

**Comment by annevk** [comment]
Wait, should we even expose when a client is gone? I know workers go out of their way not to expose that through ports. That would expose GC, no?

**Comment by jakearchibald** [comment]
For ClientID to be useful across requests you'd need to store something about that client persistently, eg in IDB. Without a way to clean up that data, it's not very useful.

**Comment by jungkees** [comment]
Issue for the new client's id filed: https://github.com/slightlyoff/ServiceWorker/issues/817

**Comment by annevk** [comment]
@jungkees you closed this, but my question isn't addressed.

**Comment by jungkees** [comment]
I thought you don't disagree to @jakearchibald's comment.

**Comment by jakearchibald** [comment]
@annevk are you suggesting `clients.get("not-a-real-id")` should returning a dummy client?

**Comment by annevk** [comment]
I'm not really sure what the lifecycle should be, but it should not be directly tied to the other side. That won't work anyway due to it all possibly being separate processes.

I guess what I'm saying is that if we solve this differently from how `SharedWorker` addresses this (requires pinging, iirc), we're violating invariants that are deemed important.

**Comment by wanderview** [comment]
I'm not sure I agree.  I don't think its the same as SharedWorker.  SharedWorker is directly reference counted and cleaned up by GC.

A client (window) can be closed through user action.  As long as the client is deemed "gone" when the user action is performed, then we're not actually exposing GC behavior.

I guess it could be an issue for a client that is a worker, though, since again those have their lifecycle managed by GC.

> I guess what I'm saying is that if we solve this differently from how SharedWorker addresses this (requires pinging, iirc), we're violating invariants that are deemed important.

Can you describe what you mean by "pinging", if its something like doing postMessage() and see if you get a response, then I'm not sure how thats different from calling clients.get(id) and getting a response.

**Comment by jakearchibald** [comment]
F2F resolution: Pages are different as removing it is user-explicit action. On navigation/close the client should not be gettable (even if it's in the back/fwd cache).

**Comment by jungkees** [comment]
The OP problem has been addressed as stated in the previous comment.

> Look into client definition. Should it be window or document/global?

We'll follow up on this one in https://github.com/slightlyoff/ServiceWorker/issues/811

Closing.

**Comment by ppppess** [comment]
Well, it seems logical to be able to identify the page using the service worker and making the requests.

In my case, I need the service worker to behave differently according to the host page url.
For example: 
if the host page location is https://myhost.com/forward then forward requests
else (the host page location is https://myhost.com/anythingElse) don't forward anything.

Any idea how can I achieve that without the clientID ?

**Comment by wanderview** [comment]
@ppppess Can you use evt.request.url for top level documents and the referrer header for sub-resources?

**Comment by ppppess** [comment]
Hi @wanderview. Sure, I guess I could hack it, but it is not as clean as being able to determin reliably which "authority" (i.e. page) controls the service worker.
Basically, no clientID makes it really hard for different pages to share the same service worker. 

You could imagine for example (silly, I know) 2 pages with the same url (referrer) opened at the same time, on the first one the user gives InstructionX, on the other InstructionY. 
With clientID, this is easy: postMessage InstructionX, service worker keeps clientID->InstructionX, and then applies InstructionX to all requests from clientID. 
Without clientID, you would have to do ugly hacks to work around the problem.
Just my 2cts. Plus it really seems logical. Or maybe I am missing something, I did not play enough with it yet. Great technology, btw.

**Comment by jakearchibald** [comment]
@ppppess what do you mean by "forward requests", as in let them go to the network rather than from a cache etc?

Assuming that's the case, and https://myhost.com/forward contained…

```html
<img src="blah.jpg">
<a href="blah.jpg">Hello</a>
```

…would you expect the client ID for the img & clicking the link to be the same?

**Comment by ppppess** [comment]
Hi @jakearchibald. Sorry, I was sloppy in my explanations. I'm gonna try to do better.

Any given page can look very different from its original state after a bunch of user clicks. 
Now imagine the user opens the same page twice in different windows, but interacts with the page differently in each wondow.

Now each window has the same url (referrer) and service worker. *But they are not in the same state*. So you may need the service worker to act differently according to the current state of the page he gets the requests from.

For example, you may want to do stuff like:
**if (req.clientID.contentWindow.button1.was.clicked) {  RespondWith("error")  }**

Easy to write, but very hard to do if you don't have the clientID info in the request.

**Comment by transformsen** [comment]
> 

Is there any solution available for fetchEvent.clientId? 
I need to know the tab/clients from where the request is triggered. In my case, Each tab is having unique id. For each fetch request I need to send the unique id of the particular tab.
