### ISSUE TITLE
What is the "Doom Installing Worker" algorithm supposed to be doing?

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#847]
Can someone tell me what the "Doom Installing Worker" algorithm is supposed to be doing?

  https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#doom-installing-worker-algorithm

As far as I can tell its run in parallel with a job from the "Run Job" algorithm.  This seems somewhat insane to me since they are both manipulating the job queue.  Isn't it incredibly racy to assume the job itself lives beyond the life of "Doom Installing Worker"?

Also, what is the purpose of the loop over the remaining items in the job queue?  It seems its trying to somehow early abort the in-parallel job iff its a register job and there is another register later in the queue.

Can we instead simply put these steps in the register job?  That would avoid races and be a lot easier to understand.

**Comment by mkruisselbrink** [comment]
As you say, Doom Installing Worker seems to try to abort installation/registration jobs if a new register job gets queued before the existing one completed. As such it is invoked both when running a job and when a new job is queued. I'm not sure if any of this is technically racy though (at least not anymore than the entire job queuing mechanism with only implied locking is; "schedule job" can run in parallel with "finish job" just as well).

Step 12 in the [install](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#installation-algorithm) algorithm seems to deal with what happens when Doom Installing Worker is executed in parallel (it aborts the rest of the steps without "finishing" the job, since the job has already been finished by Doom Installing Worker).

I do agree that it would be nice to somehow make this easier to understand, although I'm not sure how best to specify how an existing register job should be aborted when a new different register job is scheduled. Moving Doom Installing Worker to inside "register" wouldn't entirely solve it. Maybe we can replace the mentioned step 12 in the install algorithm with some check to see if a new register job got queued in the meantime, but that would still be just as racy without making explicit locking guarentees around the job queue.

**Comment by wanderview** [comment]
Why do we even need to abort the current register if a new register is appended to the queue?  How often is that going to happen in practice that we need to optimize it?  Lets just run through the queue and let both jobs run.

**Comment by wanderview** [comment]
I guess if we assume everything in the lifecycle job code runs on a single thread its not technically "racy", but I still don't understand the algorithm.  I don't see how the .installing worker could ever be set on the registration by the front job in "Doom Installing Worker" since that requires loading a worker script asynchronously.  It seems like Doom Installing Worker would just always exit at step 5.

**Comment by mkruisselbrink** [comment]
Yeah, it seems unlikely that Doom Installing Worker when called from Run Job will ever do anything useful. When Doom Installing Worker is called from Schedule Job it is of course different, as that can happen at any point while another job is installing a worker.

**Comment by wanderview** [comment]
> When Doom Installing Worker is called from Schedule Job it is of course different, as that can happen at any point while another job is installing a worker.

Hmm, yea.  "Sorry I missed where you pointed out it ran from Schedule Job."

That being said, though, it just doesn't seem safe to me.  The various algorithms don't seem designed to account for the idea that their job is going to get "Finish Job" run on it while they are in the middle some async step.

Assuming we really want this optimization I think it would be better for the algorithms to explicitly check for this cancellation at specific checkpoints.

It doesn't seem particularly perf sensitive, though, so I don't plan to implement "Doom Installing Worker" in gecko.  I'm just going to let the jobs run their course for now.

**Comment by mattto** [comment]
Yes this is what I was talking about here: https://github.com/slightlyoff/ServiceWorker/issues/783#issuecomment-168982727

DoomInstallingWorker is something I added to Chrome before we had timeouts, to ensure a while(true) worker does not block the whole job queue. I don't think it's needed in the spec, or in Chrome anymore now that we a timeout.

**Comment by mkruisselbrink** [comment]
Ah, sounds like we indeed should just get rid of it from the spec then.

**Comment by jungkees** [comment]
In Schedule Job step 2.3, the given job (Job_B here for example) is enqueued if it is not [equivalent](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#dfn-job-equivalent) to the last job (Job_A) in the queue. So, it was the only case that seemed to matter when Job_B has the same scope and a different script url with Job_A. This means, Job_B has to wait until Job_A finishes no matter how long Job_A's installing takes (e.g. caching big files, etc.) knowing that it eventually will replace Job_A's registration anyway.

If this is an edge case and doesn't seem bad, I agree to remove DoomInstallingWorker.

**Comment by mattto** [comment]
I think it's fine to wait even if the script url is different.

**Comment by jungkees** [comment]
Okay. Reading the thread, all agreed on removing it. Let's do it.
