### ISSUE TITLE
Service worker updation doesn't work as expected

### ISSUE THREAD

**Issue by RohitSharma27** [slightlyoff/ServiceWorker#946]
Hi,
As much as I understand the updation concept, SW updates when there's a byte difference in either service-worker.js or any file within it's scope.
But, it sometimes work and the other times don't. This behaviour isn't consistent. I am using sw-precache to generate my service-worker.js. If I'm posting it on a wrong forum then please let me know. I just feel that this has got to do with the behaviour of service worker and hence i am here.
P.S. : Service worker recognises the "byte" difference all the time but sometimes it does so during the first shift+reload then reload and sometimes it takes more repeated reloads. I have implemented SW on chromium v50

**Comment by wanderview** [comment]
Currently we only evaluate byte-for-byte differences in the top level service worker script.  Changes in your `importScripts()` will not trigger an update today.  (We are changing that, however.)

I think what is probably biting you is that we also honor http cache for service worker scripts.  So if you are serving your main service worker script with a max-age then you won't see updates until the cached version ages out.  (Or after 24 hours when we bypass the cache.)

We recommend that you serve your service worker script with cache-control:no-cache in order to avoid this issue.  (And we are also going to make this the default in the future.)

Does that help?

**Comment by RohitSharma27** [comment]
Thank you for the swift reply. It should work, I guess. I am going to try out your suggestion and get back with the observation. Can we update this content at [link](https://github.com/slightlyoff/ServiceWorker/blob/master/explainer.md#updating-a-service-worker)? Because it looks as if the update is triggered even if any file within the service worker gets updated, without any updation in the service-worker.js script.

**Comment by RohitSharma27** [comment]
It seems to be working all the time in my unit testing after changing the cache-control in the response header. Hence, closing this issue. 
Thanks @wanderview
